spring.datasource.url=jdbc:postgresql://localhost:5432/webshopdb
spring.datasource.username=bas
spring.datasource.password=wachtwoord1

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

fakestore.endpoint=https://fakestoreapi.com/products